### ISSUE TITLE
description and synopsis

### ISSUE THREAD

**Issue by hannesm** [samoht/dune-release#101]
not sure whether this is the right place, but opam2 now supports to integrate a `synopsis` and `descr` field in the opam file. topkg (and dune-release) have automation in place to extract a `descr` file from README.md -- what is the recommended way to dune-release-opam2 packages (and where to put `descr`)? since now lots of repositories contain multiple opam files, should they store descr individually?  or should it still be extracted from README - downside being that the descr/synopsis may be different for the different opam packages (see e.g. the mirage/mirage repository, where the description for mirage-types and mirage should be different).  so far, I manually added descr and synopsis to opam files at release time, which is tedious.

OTOH, having to manually take care of both opam and README.md is tedious as well (and will lead to out-of-sync descriptions).

**Comment by samoht** [comment]
Yes with opam2 the description and synopsis should be put in the opam file directly. This will simplify all the heuristic. Half of it already works as we are able to publish opam2 packages, but the other half don't (as #12 shown).

**Comment by Chris00** [comment]
Even is a `.descr` file exists, `dune-release` [does not upload it](https://github.com/ocaml/opam-repository/pull/12786/files).  An error should be triggered so that the user is remembered to merge those in the `opam` file.
