### ISSUE TITLE
dune-release publish failed

### ISSUE THREAD

**Issue by Chris00** [samoht/dune-release#117]
When I do `dune-release publish -v` in the repository [docker-api](https://github.com/Chris00/ocaml-docker), I get 
```
dune-release: [INFO] dune-release 1.1.0 running
dune-release: [INFO] Parsing opam file docker-api.opam
From github.com:Chris00/ocaml-docker
 * branch            gh-pages   -> FETCH_HEAD
Branch 'gh-pages' set up to track remote branch 'gh-pages' from 'origin'.
Switched to a new branch 'gh-pages'
dune-release: [ERROR] create temporary file doc/bos-b42b9a.tmp: No such file
                      or directory
```

**Comment by Chris00** [comment]
Same for [this repository](https://github.com/Chris00/ocaml-bwrap):
```
$ dune-release publish
From github.com:Chris00/ocaml-bwrap
 * branch            gh-pages   -> FETCH_HEAD
Branch 'gh-pages' set up to track remote branch 'gh-pages' from 'origin'.
Switched to a new branch 'gh-pages'
dune-release: [ERROR] create temporary file doc/bos-5aefed.tmp: No such file
                      or directory
```
`dune-release publish distrib` works, it is `dune-release publish doc` that doesn't.

**Comment by MattWindsor91** [comment]
Hmm, this seems to be happening for me too (and there's a previous issue, #114, that is the same thing) while trying to publish documentation for a new package.  I'm using macOS and version 1.1.0 from opam, if those are relevant in any way?
