### ISSUE TITLE
`--delegate github-dune-release-delegate` doesn't work

### ISSUE THREAD

**Issue by Drup** [samoht/dune-release#118]
When the delegate is improperly guessed by the heuristics, I tried to specify it by hand, but the CLI argument doesn't work, I had to use the env variable.

**Comment by NathanReb** [comment]
We're planning on deprecating delegates before removing them in `2.0.0` so I'm closing this.

The alternative is to use artifacts produced by `dune-release`'s intermediate commands in your own scripts. Delegates don't offer much more than that atm. Please reach out if you feel like you really need them so we can work out alternative solutions.
