### ISSUE TITLE
1.3.0 GitHub Pages are missing

### ISSUE THREAD

**Issue by MattWindsor91** [samoht/dune-release#155]
The [current state of the `gh-pages` branch](https://github.com/samoht/dune-release/tree/2da2c935198ef842a15bc12d1ff389feb5136742) is missing an `index.html` file (there's one in `_html` but not the root), which is causing [a 404](https://samoht.github.com/dune-release/) when trying to view the GitHub Pages for `dune-release` (as linked through the [README](https://github.com/samoht/dune-release/blob/e2f6de6525796f5ce41d393e853a0239f44c5438/README.md)).

**Comment by NathanReb** [comment]
Thanks for reporting this!

This is due to `cp -r` behaving differently if the destination directory already exists, which is the case here since we publish the documentation to the root and not in a `doc/` sub directory. I'll fix that!
