### ISSUE TITLE
publish failed

### ISSUE THREAD

**Issue by lpw25** [samoht/dune-release#156]
When trying to publish I just get:
```
dune-release: [ERROR] run ['git' '--git-dir' '.git' 'push'
                           'git@github.com:lpw25/async_graphics.git'
                      'gh-pages:gh-pages']: exited with 128
```
indeed if I run that command myself I get:
```
git --git-dir .git push git@github.com:lpw25/async_graphics.git gh-pages:gh-pages
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```
Of course the repository does exist and I have access rights for it, but that's not the style of URI that I use to access it.

**Comment by NathanReb** [comment]
Thanks for reporting this!

> Of course the repository does exist and I have access rights for it, but that's not the style of URI that I use to access it.

Just to clarify, do you mean you're using HTTPS and not SSH?

If that's the case then indeed, `dune-release` assumes SSH should be used to avoid asking you to authenticate every time it pushes. We could change that so it uses your `origin` remote to determine whether you prefer HTTPS or SSH.

In the meantime, you can add an SSH key to your github account if you want to work around that limitation.

**Comment by lpw25** [comment]
Actually, I use SSH but not with my default key. I have a `Host` in my ssh config to access github, and I also have a `[url ssh://github/] insteadOf = github:` in my `.gitconfig` to access it more easily.  This means that I need to use either: `ssh://github/lpw25/async_graphics.git` or `github:lpw25/async_graphics.git`.

> We could change that so it uses your origin remote to determine whether you prefer HTTPS or SSH.

Looking at the code, it seems like the choice of HTTPS or SSH is only used to construct a url to use as a remote. In which case why not just take the `remote` directly as an optional command line argument. Then I can just pass `--remote origin`. Also that allows for using remotes other than "origin".

**Comment by NathanReb** [comment]
This issue is similar to #172 and so are the fixes so I'm closing this one but rest assured we're working on it!
