### ISSUE TITLE
dune-release lint does not complain about missing changelog

### ISSUE THREAD

**Issue by emillon** [samoht/dune-release#158]
Hi,

I'm using dune-release 1.3.1 on a project that has a readme, opam file, etc, but no changelog (yet).

Running `dune-release lint` says that everything's fine, but `dune-release tag` fails with:

    dune-release: [ERROR] No change log specified in the package description.

I think that `dune-release lint` should try to catch that by checking for the presence of `CHANGES.md`.

How does that sound?

Thanks!

**Comment by NathanReb** [comment]
Thanks for the report, I'll add that check!
