### ISSUE TITLE
`dune-release lint` errored on my "valid" OPAM file

### ISSUE THREAD

**Issue by dinosaure** [samoht/dune-release#166]
When I launch `dune-release lint` (1.3.2) into: https://github.com/mirage/checkseum/commit/f2738d121b460c53708f05f92ff8e1512e124e73

I get an error: `could not parse opam file`. However, `opam lint` (2.0.3) validate the same OPAM file. `dune-release distrib` works in other side.

**Comment by NathanReb** [comment]
I could not reproduce the bug for some reason. Can you retry from https://github.com/mirage/checkseum/commit/f2738d121b460c53708f05f92ff8e1512e124e73 with a clean repo and see if you still have the error?

**Comment by dinosaure** [comment]
I think, I missed `eval $(opam env)` or something like this and used an old version of `dune-release`. The bug does not exist anymore with a fresh `ocaml.4.08.0` and `dune-release.1.3.2`.
