### ISSUE TITLE
`publish distrib` and 2FA

### ISSUE THREAD

**Issue by Drup** [samoht/dune-release#18]
I have 2FA enabled, and I basically never use the https auth for github (I always go through ssh).

When trying to use `publish distrib`, I get a 401 that ends with this:
```
{
"message": "Must specify two-factor authentication OTP code.",
"documentation_url": 
  "https://developer.github.com/v3/auth#working-with-two-factor-authentication"
}
```

I guess there is an extra step needed.
Alternatively, dune-release could direct me to the page for creating personal access tokens.

**Comment by samoht** [comment]
Should be fixed by #7 

The tool will now ask you to create the token with GitHub web UI.
