### ISSUE TITLE
Customize the opam file before distrib creation

### ISSUE THREAD

**Issue by Drup** [samoht/dune-release#19]
Sometimes, you might want to tweak the opam file a little bit before doing a release. For example, I like to change the `doc` field to point to the right version of the documentation. It would be nice if `dune-release` supported that.

**Comment by samoht** [comment]
Do you want a manual or automatic process to do that?

**Comment by Drup** [comment]
That's actually a good question. Most changes could be made automatically but I'm not sure a patch system would be sufficient. Maybe with additional variables (`%%VERSION%%` and the like). In all cases, I really want to manually inspect the opam file before pressing the big red button, so `dune-release` should definitely show it to me.

**Comment by NathanReb** [comment]
I believe the current split between the `dune-release opam pkg` and `dune-release opam submit` commands is what you're looking for so I'm closing this.

Please re-open if this doesn't fix your problem.
