### ISSUE TITLE
Multi-package workings unclear

### ISSUE THREAD

**Issue by Leonidas-from-XIV** [samoht/dune-release#54]
When I try to release `ocaml-zmq` which has `zmq`, `zmq-lwt` and `zmq-async` as subpackages it works in a way I would not expect.

When I do `dune-release distrib` it generates one single tarball. This is a bit surprising, but since it includes all the source for all subpackages this might be the right thing to do.

But when I do `dune-release opam pkg -p zmq,zmq-async,zmq-lwt` (a bit strange I have to mention all of them) it does

```
Wrote opam package _build/zmq.5.0.1
Wrote opam package _build/zmq.5.0.1
Wrote opam package _build/zmq.5.0.1
```

And the file it generates is just derived from `zmq.opam`.

**Comment by samoht** [comment]
Should work better in master. Could you have a try and re-open if the workflow is unclear? Thanks!
