### ISSUE TITLE
Tag detection is broken

### ISSUE THREAD

**Issue by Drup** [samoht/dune-release#56]
Tag detection seems to rely on several things, and sometimes ignores what you give on the command line or what is present in `_build`. For my last tyre release, it insisted that it was 0.1 while 0.4 was tagged in the repository.

That was with last versions of dune and dune-release.

**Comment by Drup** [comment]
This might be due to the fact that my tag was "0.4" and not "v0.4".

**Comment by samoht** [comment]
This should be fixed in master. There is now a `--tag` option to specify the tag you want to release/distribute.
