### ISSUE TITLE
Can't publish when changelog doesn't have the precise format.

### ISSUE THREAD

**Issue by Drup** [samoht/dune-release#58]
My changelog has a title at the beginning, which makes dune-release completely bork in a way that I can't bypass with the command line: 

```
% dune-release publish distrib --dist-ver 0.4
fatal: Needed a single revision
dune-release: [ERROR] CHANGES.md lists 'Change' as the latest release, but no
                      corresponding tag has been found in the repository.
                      Did you forget to call 'dune-release tag' ?
```

My changelog: https://github.com/Drup/tyre/blob/master/CHANGES.md

Latest version of dune and dune-release.

**Comment by samoht** [comment]
Normally this should be fixed in master where you can use the `--tag` option to select which tag to distrib/publish from.
