### ISSUE TITLE
Publish to org doc URL fails

### ISSUE THREAD

**Issue by mor1** [samoht/dune-release#59]
```
dune-release: [ERROR] Could not derive publication directory $PATH from opam
                      doc field value "https://owlbarn.github.io/"; expected
                      the pattern $SCHEME://$USER.github.io/$REPO/$PATH
[FAIL] lint _build/owl-0.4.0 failure: 1 errors.
```
For this particular package (Owl), the docs are intended to be published as the `owlbarn` org website, so no `$REPO` or `$PATH` components provided.

(Possibly an edge case I admit :)

**Comment by NathanReb** [comment]
The error should soon go away as we are going to drop parsing of `doc` and `home` and always work with `dev-repo`.

I"m closing this but if you really want `dune-release` to allow you to publish the doc elsewhere on github please re-open and we'll try to work something out with a local release config.
